Squashed version of inf-312-{split-importers,parser-abc}
commit 5f781bb86a64b5933e11e7ca170dc0cf24df4012
Author: Infernio <infernio@icloud.com>
Date:   Wed Mar 25 19:15:24 2020 +0100

    TES5: Reenable Aliases patcher

    Disabled in e472bd26c3637df0a848031a4fbd623600d382d9 because there were
    no patchers for Skyrim that could make use of it (i.e. patchers that can
    read CSV files as well as plugin files), but now we have importing (and
    more importantly, exporting) functional for a few of them (e.g. Import
    Factions), so this patcher is now useful.

commit cd277a8eae0b2e2879572eb240f90a06ec94f834
Author: Infernio <infernio@icloud.com>
Date:   Sat Sep 28 20:51:21 2019 +0200

    Rework Import Relations

    Now works for Skyrim-based games, FO3 and FNV. We had it enabled for
    FO3 and FNV, but it wasn't actually working - that was the cause of
    the elusive 'groupCombatReaction' traceback.

    Note that the readme claimed that it could handle deletions as well - it
    could not. I introduced a new tag, Derel, that makes the BP carry
    forward deletions. Obviously PBash-only.

    TODO: Drop the id_deleted parts after inf-312-split-importers has
    refactored ImportRelations to be a merger.

    TODO: Rename Relations/Derel to Relations.{Add,Remove} once refactored

commit dc5befc9575a066ac7ab0167079b285a18ea6f23
Author: Infernio <infernio@icloud.com>
Date:   Fri Sep 27 23:04:37 2019 +0200

    Refactor FactionRelations to use _AParser

    Added some functionality to become Skyrim-compatible in the next commit,
    that's why the added line count is unusually high.

    See how similar _write_record is to the one from ActorFactions? Could
    probably create an abstract class for this, but we'll worry about that
    later - this refactoring will likely expose many such opportunities for
    follow-up refactoring.

commit 55fb62b01644944ca7528e7730dbe44233c8d5dd
Author: Infernio <infernio@icloud.com>
Date:   Sat Sep 28 23:40:29 2019 +0200

    TES5: Add Import Factions support

    No idea why this was using any of that nonsense, it's just a dead simple
    'preserves' patcher and can therefore use the 100% standard
    _SimpleImporter pattern. It looks like it may have been based off of the
    Import Relations patcher, and was intended to merge additions and
    deletions, but during development its author decided that was a bad
    idea and made it a standard preserver. In fact, that seems to be what
    the CBash patcher does - however, IMO the 'preserves' behavior makes
    more sense here, so we should adjust the CBash patcher at some (distant)
    point.

    Please excuse the fact that this makes the Oblivion links no longer
    sorted, will fix itself once everything is refactored :)

commit 0cbad1627497f4143fa7d2fa7f3dc417ff34c992
Author: Infernio <infernio@icloud.com>
Date:   Fri Sep 27 17:10:41 2019 +0200

    Refactor ActorFactions to use _AParser

    Nice savings so far, looks quite promising.

commit 24363afb79da6ee5f78a9ca5f1eb74b6c299d8ed
Author: Infernio <infernio@icloud.com>
Date:   Wed Mar 25 20:41:21 2020 +0100

    Auto-enable export/import links

    Based on the record types of the parsers. Will massively simplify the
    mess that is the import/export section in links_init.py.

    Also sorted the Oblivion sections.

commit afe8f30fbdf6ddc12d1ffeec8bf4b0a067d16cf0
Author: Infernio <infernio@icloud.com>
Date:   Wed Mar 25 18:10:39 2020 +0100

    XXX revert part of CSV POC

    Currently so WIP that it breaks the patchers :P

commit bf18f72a3e990971b8ee54afde9c995dda268d56
Author: Infernio <infernio@icloud.com>
Date:   Thu Oct 3 00:59:26 2019 +0200

    POC: Half-baked CSV format attempt

    Need to study how the actual CSV files look, but I keep getting
    weird tracebacks (probably due to wine) when I try to export some mods
    for testing.

commit c9bb85559e0ecaa321f627cc1c00ac527614f29b
Author: Infernio <infernio@icloud.com>
Date:   Fri Sep 27 17:10:41 2019 +0200

    POC: Attempt at a parser ABC

    Already more performant and much less noisy than the previous
    copy-pasted spaghetti mess. Still needs to absorb the methods for
    reading/writing text.

commit 2e751690aad47a92b89a48e90291dbcbbb76b79f
Author: Infernio <infernio@icloud.com>
Date:   Thu Jul 23 23:31:32 2020 +0200

    Squashed version of inf-312-split-importers

    commit bf40794a1d12906753a54b15ff6f23056aca388f
    Author: Infernio <infernio@icloud.com>
    Date:   Thu Jul 23 01:16:05 2020 +0200

        Absorb NamesPatcher into _APreserver

        The CELL/WLRD stuff in there was unused (CELL and WRLD were not listed
        in any game's namesTypes). Which is good, because it didn't work.

        I would like to get it working and add CELL/WRLD to namesTypes (as well
        as readding DIAL, which I had to remove from Skyrim), plus this is a
        good step in the direction of absorbing CellImporter.

    commit 7b5b8759f8a9d1deda82675b84524a780c79322c
    Author: Infernio <infernio@icloud.com>
    Date:   Thu Jul 23 00:48:03 2020 +0200

        Absorb SpellsPatcher into _APreserver

        We're getting somewhere :)

    commit 8d49e1380f5e7933dc4ed99e625d007fa491a931
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 22:53:41 2020 +0200

        New tag: NPC.AIPackageOverrides

        Per request on Discord. Part of Import Actors, patches SPOR, OCOR, GWOR
        and ECOR.

        Also took this opportunity to drop the pointess actor_importer_auto_key
        constant.

    commit 5b2f2fb1117414bc84765fe6cfe402ee57c7f0b1
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 18:45:24 2020 +0200

        Absorb StatsPatcher into _APreserver

        I've declared war on _parse_sources.

        Only thing 'needed' to absorb this one was the small id_records part of
        scanModFile, which should just be a small performance improvement as
        explained in the new comments there.

    commit 7185b8e041b83a5a7059cf7bc4321c491878138d
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 18:30:57 2020 +0200

        Absorb ImportFactions into _APreserver

        No idea why this was using any of that nonsense, it's just a dead simple
        'preserves' patcher and can therefore use the 100% standard
        _APreserver pattern. It looks like it may have been based off of the
        Import Relations patcher, and was intended to merge additions and
        deletions, but during development its author decided that was a bad
        idea and made it a standard preserver. In fact, that seems to be what
        the CBash patcher does. We should weight our options here in the future
        and either make this a merger or keep it as a preserver. Either one is
        much easier now that it's absorbed :)

        Leaked from future parser-abc merge.

    commit 8c212e6368bd3270b55e9f1c0fe76a21d88844ab
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 23:18:19 2020 +0200

        Add CSV parsing support to _APreserver

        In preparation for absorbing all those _parse_sources-based patchers.
        Unfortunately, this implementation simply copies all records listed in
        the CSV file into the patcher without checking for ITMs/ITPOs.
        Considering that this is an extremely rarely used feature and fixing
        this would require considerable effort, I'm just not going to bother.

    commit bb35f295bc4c328d0c24ad7b1d5eda545eb849f9
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 18:05:44 2020 +0200

        Move setattr differences to class variable

        Allows dropping two more overrides, absorbing WeaponModsPatcher fully in
        the process.

    commit 3c15f19903ad977019407e9e727c02d6ff4a2901
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 18:14:01 2020 +0200

        Absorb ActorImporter into _APreserver

        _init_data_loop is only called once per src, so need to worry about
        performance. The _inner_loop override will be dropped in the next
        commit.

        Only one override of _init_data_loop left :)

    commit 2e5e3031a60180525c0902654e5df861514e9eba
    Author: Infernio <infernio@icloud.com>
    Date:   Thu Jul 23 00:37:10 2020 +0200

        Rename _SimpleImporter -> _APreserver

    commit e4f506970c71d8b7f9eb783ae94b4c26937b2ad9
    Author: MrD <the.ubik@gmail.com>
    Date:   Thu Apr 30 16:12:35 2020 +0300

        Use attrgetter instead of reduce

        from operator import attrgetter
        class A(object): pass
        class B(A): pass
        a = A()
        a.b = B()
        a.b.c = 'hello'
        print(attrgetter(u'b.c'))(a)
        hello

        In theory faster too

        More attrgetter - drop overrides in importers!

        cint reduce XXX

        Wip _AttrGettersCache(dict)

        actor_importer_attrs -> never a tuple in there?

        Note that

        {}[[]]
        Traceback (most recent call last):
          File "<input>", line 1, in <module>
        TypeError: unhashable type: 'list'

        so the isinstance(attr, (list, tuple, set)): make not sense, only tuple
        should be accepted

        DestructiblePatcher -> never has a 'model' attr ? TTT

        Infernio:
        You should be able to drop the _inner_loop here. destructible is only
        ever a MelDestructible instance, so can't be a string, which should
        make the behavior of this loop identical to its parent.

        Same NB as with the other one though [WeaponMods] - this doesn't do
        anything right now, but may have been intended to handle
        case-insensitive comparisons of destructible.stages[i].model.

        WeaponModsPatcher -> again no model? XXX

        Infernio
        You should be able to drop the string comparison logic here. The
        'splitting by dots' logic is still required, but none of these attrs
        can be strings at runtime:

        modelWithMods - MelObject
        firstPersonModelWithMods - MelObject
        weaponMods - MelObject
        soundMod1Shoot3Ds - list of fids
        soundMod1Shoot2D - fid
        effectMod1 - int
        effectMod2 - int
        effectMod3 - int
        valueAMod1 - float
        valueAMod2 - float
        valueAMod3 - float
        valueBMod1 - float
        valueBMod2 - float
        valueBMod3 - float
        reloadAnimationMod - int
        vatsModReqiured - int
        scopeModel - MelObject
        dnamFlags1.hasScope - bool, but special case because of dot
        dnamFlags2.scopeFromMod - bool, but special case because of dot

        That said, my guess is that the string comparison logic was meant to
        apply to modelWithMods, firstPersonModelWithMods and weaponMods, and
        the model comparison logic to scopeModel. So maybe we should keep it
        and fix it up to use those instead?

        Upon thinking on this further, maybe the right place to handle this
        case insensitivity isn't in the patchers, but in the records. We
        could make a MelCIString that turns the read string into a CIStr.
        That way all this patcher-specific logic could disappear.

        Utumno:
        > this case insensitivity isn't in the patchers, but in the records.

        Aaahhh - yes - but I want to get rid of the decoding/encoding on
        loadData and dumpData. I guess - cause it is difficult to trace what
        attribute of the records is used where, especially if it's called eid
        - that most of the time those are decoded and then are unused and
        then encoded - and apart from the performance that this costs, it
        might lead to mangled up strings if that decoding/encoding messes up
        (falling back to mbcs) - and we won't even know.

        We really have to go through what encodings are really accepted (by
        the game) in the string fields - possibly only cp1252?[1] This
        started cause some mods encode some fields differently - but maybe it
        will turn out that anyway apart from, say, 'description' nothing else
        can be in Unicode, so we will compare byte-strings as byte-strings
        for a lot of performance (and simpler code). Or not...

        Case insensitivity is another fruit - but then to me the basic issue
        is finding a way of doing the decoding/encoding/case-normalizing JIT.
        I thought of dynamically adding properties to the records that wrap
        the (now renamed to _eid say) string fields but this is getting messy
        and complex. I thought about metaclasses (god forbid) or patching the
        getSlotsUsed or... - but nothing yet as I just now start to grok the
        records (thanks to your rewrite), and the dynamical nature of records
        code does not help to trace what is used where.

        > That said, my guess is that the string comparison logic was meant to
        apply to modelWithMods

        The special treatment of model is another oops - if we want to test
        model.modPath then we should have in our arrays model.modPath and
        hand along to the attrgetter (neat eh?) like the rest. Special cases
        is what one wants to eliminate

        For now, I will go ahead and rip those overrides off as you
        commented, so we can revisit the long ids thing - although what I
        would hope to get into nightly is prefixing, I regret adding dirs
        prefixes as the right way is those unicode literals, as then we test
        on py2 already (and convert all pickled strings to unicode for users
        to have in their settings before py3)

        And when the dust settles time for a simple_importers.py I think

        Ref # 480, # 232

        [1] we might then as well say str.dedode(u'cp1252') except
        UnicodeDecodeError -> warn user that field X in record Y seems not
        game readable.

        lojack5:
        I think from Skyrim on it's ok to always assume cp1252, some they
        added translation strings.

        On Oblivion for sure (and maybe Fallout 3 / NV?), Things are a mess
        though. Both Chinese and Japanese are not supported by the game.
        Either one or both of the languages (ive forgotten which) modders
        have gotten to work by monkey patching the engine with a plug-in
        (OBSE I think). I'd have to see if I ha e any of my correspondence
        with valda to check though, at one point he sent me whatever they use
        so I could test.

        I'm not sure what Russian and other Cyrillic languages do though,
        they may have a plug-in as well. The other big western European
        languages have their own official game exe, I'm not sure if those use
        a codepage but they might.

        All of which to say, might need to implement it on a per game basis.
        Not decoding would of course be an easy fix as well, although things
        like importing/exporting npc names to/from csv and similar things
        would have to have their encoding/decoding checked to work with that.

        lojack5:
        Found the Japanese patch: http://jpmod.oblivion.z49.org/

        -----

        FFF _setattr_deep

        setup = """
        class A(object):
            def __init__(self, a):
                self.a = a

        a = A(5)
        """
        print(timeit.timeit('a.__setattr__(u"a", 5)', setup))
        print(timeit.timeit('setattr(a, u"a", 5)', setup))

        0.11508789999999997
        0.07353180000000004

        took also ActorImporter one along

        some more caching FFF

        Before:

        patcher_dialog.py  215 PatchExecute:          560913348 function calls (504538508 primitive calls) in 252.848 seconds

        After:

        patcher_dialog.py  215 PatchExecute:          560128783 function calls (503753943 primitive calls) in 253.211 seconds

        700k function calls less

        Infernio: Dropped changes to ImportRelations to avoid conflicts with
        inf-312-parser-abc

    commit 4667b2e12c74c137950a2d824ba5ffde60314547
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 17:39:05 2020 +0200

        Split importers.py into four new files

        Also rename Oblivion's importers.py -> preservers.py

    commit ecbb8c0c0f075b83d8d172fcc00ead5ef52e1488
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 17:34:25 2020 +0200

        Alias ancient 'Spells' tag to SpellStats

        Never heard of it, but it looks like it was a thing once?

    commit 471b60ddaea0acc3527a43a9a6cfc4d6ec7d64d7
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 16:59:56 2020 +0200

        TES5: Add Import Outfits patcher

        Merges changes to OTFT records. It worked on the first try, so I'm super
        suspicious of it :P

    commit 40575d21b59ff77ceee2d2b93c926c89e07a4562
    Author: Infernio <infernio@icloud.com>
    Date:   Wed Jul 22 16:57:14 2020 +0200

        Rip out a base class from ImportInventory

        Still very WIP, but looks promising. Current major pain points are
        listed in the code, but for completeness' sake also here:
         - currently relies on the merged subrecord being sorted
         - lacks ForceAdd support
         - can't absorb the other mergers until the two points above are
           addressed

commit a82925ecb6ce08d8844689e4c9952f7691b67b10
Author: Daniel Nunes <daniel.henri.nunes@gmail.com>
Date:   Tue Dec 3 03:58:08 2019 +0000

    Add string prefixes to parsers

    Ut:

    note

    @@ -4022,3 +4022,3 @@ def load(self, do_unpack=False, progress=None, loadStrings=True):
                             insSeek(size - header.__class__.rec_header_size, 1,
    -                                u'%s.%s' % (type, label))
    +                                u'%s.%s' % (type.decode(u'ascii'), label))
                     except:

    Infernio: I dropped all of the ones that edited stuff that got moved to
    mod_files.py - wasn't much plus most wouldn't have worked on py3 anyways
    (getattr(modFile, b'NPC_') is an error on py3).